version: "3.8"
services:
  db:
    image: mariadb:11
    env_file:
      - .env.docker
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./src/lib/without_data.sql:/docker-entrypoint-initdb.d/without_data.sql:ro

  app:
    build: .
    ports:
      - "4321:4321"
    env_file:
      - .env.docker
    depends_on:
      - db

volumes:
  db_data:
